#!/bin/bash

REPO="https://raw.githubusercontent.com/COLD1224/AgateRepository/main/downloads"

case "$1" in
    help)
        echo "Agate Package Manager"

        echo "commands:"
        echo "inst (installs APkgs)"
        echo "gtrd (removes APkgs)"
        echo "help (shows commands again)"
        echo "list (shows APkg names and their download acronyms)"
echo "made by Gemstone!"
        ;;
    inst)
        wget -4 -q -O packages.txt "https://raw.githubusercontent.com/COLD1224/AgateRepository/main/packages.txt"

        while IFS='|' read -r id name path;
        do
           if [[ "$id" == "$2" ]]; then
                echo "Found APkg: $name"
                echo "Path: $path"
                sleep 1
                echo "installing.."
                url="$REPO/$path"
                filename=$(basename "$path")

                wget -4 -q -O "$filename" "$url"
                echo  "installed $name!"
                chmod +x "$filename"

		sleep 2
		rm packages.txt
           fi
        done < packages.txt
        ;;
    gtrd)
	wget -4 -q -O packages.txt "https://raw.githubusercontent.com/COLD1224/AgateRepository/main/packages.txt"

	while IFS='|' read -r idrm name path;
	do
	 if [[ "$idrm" == "$2" ]]; then
		echo "Found APkg: $name"
        	echo "Path: $path"
	   	echo "removing.."
	   filename=$(basename "$path")

	 rm "$filename"
	#sx
	 sleep 2
         #i dont like when it when the yellow squares appear on my terminal
	#so im doing this, and im typing this for the people who would read my files
	#- AreuAzure (Owner!) from Gemstone
	echo "removed $filename"
	fi
	sleep 1
	done < packages.txt
	sleep 1
	rm packages.txt
        ;;
    list)
        echo "APkg list:
                azureland (al)
                DevTooz (dtz)
                FastStart (fs)"
        ;;
    *)
        echo "Unknown command. check 'agate help' maybe you misspelled it."
        ;;
esac
