#!/bin/bash

REPO="https://raw.githubusercontent.com/COLD1224/AgateRepository/main/downloads"

case "$1" in
    help)
        echo "Agate Package Manager"

        echo "commands:"
        echo "inst (installs package)"
        echo "rm (removes package)"
        echo "help (shows commands again)"
echo "made AGLT (Azure Gemstone Linux Tools/Stuff)"
        ;;
    inst)
        while IFS='|' read -r id name path;
	do
	   if [[ "$id" == "$2" ]]; then
		echo "Found APkg: $name"
		echo "Path: $path"
		url="$REPO/$path"
		filename=$(basename "$path")

		wget -4 -O "$filename" "$url"
	   fi
	done < ../packages.txt
        ;;
    rm)
        # remove package
        ;;
    *)
        echo "Unknown command. check 'agate help' maybe you misspelled it."
        ;;
esac

